version: "3.8"
services:
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: araqr
